import os
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from agent.tools import predict_property_price, get_comparable_properties
from utils.report_formatter import format_report

try:
    from rag.retriever import search_text_database
except ImportError:
    def search_text_database(query: str, max_results: int = 3):
        return ["RAG System not built yet."]


def intake_node(state: dict) -> dict:
    return state


def price_prediction_node(state: dict) -> dict:
    property_details = state["property_features"]
    
    prediction_result = predict_property_price.invoke({"features": property_details})
    
    state["predicted_price"] = prediction_result["predicted_price"]
    state["price_range"]     = prediction_result["price_range"]

    similar_properties = get_comparable_properties.invoke({
        "location": str(property_details.get("latitude", "Unknown Area")),
        "price": state["predicted_price"],
        "size": property_details.get("total_flat_area", 1500)
    })
    state["comparable_properties"] = similar_properties
    
    return state


def rag_retrieval_node(state: dict) -> dict:
    search_query = (
        f"Real estate market trends. "
        f"Investment outlook for properties around ${state['predicted_price']}."
    )
    
    helpful_documents = search_text_database(search_query, max_results=3)
    state["retrieved_market_docs"] = helpful_documents
    
    return state


def market_analysis_node(state: dict) -> dict:
    api_key = os.getenv("GROQ_API_KEY", "")
    
    if not api_key or api_key == "your_groq_api_key_here":
        state["market_analysis"] = "Groq API key is missing. Add it to .env to enable the AI writer."
        return state

    ai_model = ChatGroq(
        model_name="llama-3.1-8b-instant",
        temperature=0.3,
        groq_api_key=api_key
    )

    found_context = "\n".join(state.get("retrieved_market_docs", []))
    
    system_rules = "You are a professional real estate analyst. Be concise."
    user_request = f"""
    Write a short 2-paragraph market analysis for a property.
    Predicted Price: ${state['predicted_price']:,.2f}
    
    MARKET CONTEXT (Read this to get your facts):
    {found_context}
    
    RULES:
    - Never invent statistics that are not in the context.
    - End with a one-sentence investment risk summary (Low/Medium/High).
    """

    messages = [
        SystemMessage(content=system_rules),
        HumanMessage(content=user_request)
    ]
    ai_response = ai_model.invoke(messages)
    
    state["market_analysis"] = ai_response.content
    return state


def report_generation_node(state: dict) -> dict:
    """Step 5: Organize all the data into a clean, presentation-ready format."""
    state["advisory_report"] = format_report(state)
    return state


def disclaimer_node(state: dict) -> dict:
    """Step 6: Stamp a legal warning at the end of the report."""
    legal_warning = (
        "**LEGAL DISCLAIMER:** This report has been generated by an AI assistant "
        "and is for informational purposes only. It does not constitute professional "
        "financial or legal advice. The machine learning price predictions are estimates "
        "based on historical data and may not reflect current market conditions."
    )
    
    if "advisory_report" in state and isinstance(state["advisory_report"], dict):
        state["advisory_report"]["disclaimer"] = legal_warning
        
    return state
