import os
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

from agent.tools import predict_property_price, get_comparable_properties
from utils.report_formatter import format_report

# We will build this RAG file in the next step (Step 5)
try:
    from rag.retriever import query_rag
except ImportError:
    # Fallback if RAG isn't built yet
    def query_rag(query: str, top_k: int = 4):
        return ["RAG System not fully initialized yet."]


def intake_node(state: dict) -> dict:
    """1. Checks if all required inputs are present."""
    # In a real app we'd validate required fields here.
    # For now, we trust the Streamlit form provided them.
    return state


def price_prediction_node(state: dict) -> dict:
    """2. Runs the joblib ML model to predict property price."""
    features = state["property_features"]
    
    # We pass features as a dict inside another dict to match LangChain's Tool schema
    result = predict_property_price.invoke({"features": features})
    
    state["predicted_price"] = result["predicted_price"]
    state["price_range"]     = result["price_range"]

    # Also grab comparable properties (synthetic data for this project)
    comps = get_comparable_properties.invoke({
        "location": str(features.get("latitude", "Unknown")),
        "price": state["predicted_price"],
        "size": features.get("total_flat_area", 1500)
    })
    state["comparable_properties"] = comps
    
    return state


def rag_retrieval_node(state: dict) -> dict:
    """3. Searches FAISS vector store for relevant market advice."""
    # Build a query based on we know so far
    query = (
        f"Real estate market trends for area. "
        f"Investment outlook for properties around ${state['predicted_price']}."
    )
    docs = query_rag(query, top_k=3)
    state["retrieved_market_docs"] = docs
    return state


def market_analysis_node(state: dict) -> dict:
    """4. Uses Groq LLM + RAG documents to write a market analysis."""
    # Initialize the Groq model
    api_key = os.getenv("GROQ_API_KEY", "")
    if not api_key or api_key == "your_groq_api_key_here":
        state["market_analysis"] = "Groq API key is missing. Please set it in the .env file to enable Market Analysis."
        return state

    llm = ChatGroq(
        model_name="llama-3.1-8b-instant",
        temperature=0.3,
        groq_api_key=api_key
    )

    context = "\n".join(state.get("retrieved_market_docs", []))
    
    sys_prompt = "You are a professional real estate market analyst. Be concise."
    user_prompt = f"""
    Write a short 2-paragraph market analysis for a property.
    Predicted Price: ${state['predicted_price']:,.2f}
    
    MARKET CONTEXT (Use ONLY this information):
    {context}
    
    RULES:
    - Never invent statistics or facts not present in the context.
    - End with a one-sentence investment risk summary (Low/Medium/High).
    """

    messages = [
        SystemMessage(content=sys_prompt),
        HumanMessage(content=user_prompt)
    ]
    
    response = llm.invoke(messages)
    state["market_analysis"] = response.content
    return state


def report_generation_node(state: dict) -> dict:
    """5. Formats everything into a clean presentation string."""
    state["advisory_report"] = format_report(state)
    return state


def disclaimer_node(state: dict) -> dict:
    """6. Appends the mandatory legal disclaimer."""
    disclaimer = (
        "**LEGAL DISCLAIMER:** This report has been generated by an AI assistant "
        "and is for informational purposes only. It does not constitute professional "
        "financial or legal advice. The machine learning price predictions are estimates "
        "based on historical data and may not reflect current market conditions."
    )
    
    if "advisory_report" in state and isinstance(state["advisory_report"], dict):
        state["advisory_report"]["disclaimer"] = disclaimer
        
    return state
